services:
  nagios-core:
    build: .
    container_name: nagios-core
    ports:
      - 80:80
    image: "jtkowtko/nagios-core:1.1"
    hostname: nagios-core
    restart: always
    volumes:
      - ./config:/usr/local/nagios/
