services:
  nagios-core:
    build: .
    container_name: nagios-core-4.5.2
    ports:
      - 80:80
    image: "jtkowtko/nagios-core:latest"
    hostname: nagios-core
    restart: always
#    volumes:
#      - ./4.5.2/nagios:/usr/local/nagios/
