services:
  nagios-core:
    build: .
    container_name: nagios-core
    ports:
      - 80:80
    image: "nagios-core:latest"
    hostname: nagios-core
#    volumes:
#      - ./config:/usr/local/nagios
